/**
 * Per-route SEO metadata + JSON-LD structured data.
 *
 * Each tool page gets a title aimed at its search query, a description
 * with the privacy hook, and a WebApplication JSON-LD block.
 * Rendered during prerendering so crawlers see the full document.
 */
import { site, siteUrl } from './config';

export interface RouteMeta {
  title: string;
  description: string;
  /** Open Graph image — generated by scripts/og-image.mjs. */
  image?: string;
}

const ogImage = `${siteUrl}/og.png`;

export const routeMeta: Record<string, RouteMeta> = {
  '/': {
    title: `${site.name} — Free, Secure & Private Browser Tools (100% in Your Browser)`,
    description:
      'Free, secure tools that run entirely in your browser: guitar tuner, JSON/YAML formatter, regex checker, ' +
      'string escaper, date/time converter, JWT decoder, compass, level and ruler. ' +
      'No uploads, no accounts — everything stays on your device.',
    image: ogImage,
  },
  '/guitar-tuner': {
    title: 'Guitar Tuner Online — Free, Private, In-Browser (No Upload) | ToolsBoogie',
    description:
      'Tune your guitar right in the browser. A live pitch detector listens to your strings through the ' +
      'microphone and shows note, cents deviation and a spectrum — all on your device, nothing is recorded.',
    image: ogImage,
  },
  '/json-format': {
    title: 'JSON Formatter & Minifier — Free, Private, In-Browser | ToolsBoogie',
    description:
      'Pretty-print, minify and validate JSON with exact line and column error positions. ' +
      'Runs in your browser — your data is never uploaded. Free JSON formatter with sort-keys option.',
    image: ogImage,
  },
  '/json-to-yaml': {
    title: 'JSON to YAML Converter — Free, Private, In-Browser | ToolsBoogie',
    description:
      'Convert JSON to clean, human-readable YAML — entirely in your browser. No upload, no account, ' +
      'your data never leaves your device. Free JSON to YAML converter.',
    image: ogImage,
  },
  '/yaml-format': {
    title: 'YAML Formatter & Validator — Free, Private, In-Browser | ToolsBoogie',
    description:
      'Validate and re-format YAML documents (or convert them to JSON) right in your browser. ' +
      'Runs 100% client-side — nothing is uploaded. Free YAML formatter.',
    image: ogImage,
  },
  '/regex': {
    title: 'Regex Checker & Builder — Test Regex in-Browser, Linted per Engine | ToolsBoogie',
    description:
      'Test regular expressions instantly against live input, see every match and capture group, and get ' +
      "warnings when a pattern uses features your target engine (JavaScript, Python, Go, Java, PCRE, POSIX) won't " +
      'understand. Includes a builder palette and a common-pattern cheat sheet. 100% in your browser.',
    image: ogImage,
  },
  '/string-escape': {
    title: 'String Escaper & Unescaper — JSON, JS, C, HTML, Shell, URL | ToolsBoogie',
    description:
      'Escape or unescape strings for JSON, JavaScript, Java, C, Python, Rust, HTML entities, URL components, ' +
      'shell, SQL and Unicode — right in your browser. Free, private, no upload.',
    image: ogImage,
  },
  '/time': {
    title: 'Date & Time Converter — Epoch, ISO 8601, FILETIME, Timezones | ToolsBoogie',
    description:
      'Convert dates and timestamps between ISO 8601, RFC 2822, UNIX epoch (s/ms/µs/ns), Windows FILETIME, ' +
      '.NET ticks, SQL and more, in any IANA timezone. Outputs ready to paste into Python, pandas, Go, C, ' +
      'Linux date and JavaScript. 100% in your browser.',
    image: ogImage,
  },
  '/jwt': {
    title: 'JWT Decoder & Encoder — Decode, Edit & Re-sign Tokens In-Browser | ToolsBoogie',
    description:
      'Decode JWTs, inspect claims, edit header and payload, and re-sign with HS256/384/512, RS256/384/512 ' +
      'or ES256/384/512 — entirely in your browser via WebCrypto. Secrets and keys never leave your device.',
    image: ogImage,
  },
  '/compass': {
    title: 'Online Compass — Digital Compass in Your Browser (Free, Private) | ToolsBoogie',
    description:
      'A digital compass that uses your device sensors for a live true heading. Works on phones and ' +
      'tablets; runs entirely in the browser — no data is collected.',
    image: ogImage,
  },
  '/ruler': {
    title: 'Online Ruler — Metric & Imperial On-Screen Ruler | ToolsBoogie',
    description:
      'A dual-edge on-screen ruler — centimetres on the left, inches on the right. It calibrates itself from your screen ' +
      'or takes your display size, and measures any distance in the browser. Free, private, no upload.',
    image: ogImage,
  },
  '/level': {
    title: 'Digital Level — Bubble Level in Your Browser (Free, Private) | ToolsBoogie',
    description:
      'Turn your device into a bubble level: live tilt in degrees from the accelerometer, ' +
      'a virtual bubble and a calibrate button. Runs entirely in the browser — no uploads.',
    image: ogImage,
  },
  '/privacy': {
    title: `Privacy — ${site.name}`,
    description:
      'How ToolsBoogie works: every tool runs locally in your browser. Nothing is uploaded, stored or ' +
      'transmitted. Read the full privacy policy.',
  },
};

/**
 * JSON-LD per route: the home page advertises a SoftwareApplication suite,
 * each tool page its own WebApplication.
 */
export function jsonLdFor(route: string): Record<string, unknown> {
  const meta = routeMeta[route] ?? routeMeta['/']!;
  const base = {
    '@context': 'https://schema.org',
    name: site.name,
    url: `${siteUrl}${route === '/' ? '' : route}`,
    description: meta.description,
    image: meta.image,
  };
  if (route === '/') {
    return {
      ...base,
      '@type': 'WebApplication',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Any',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    };
  }
  return {
    ...base,
    '@type': 'WebApplication',
    applicationCategory: 'UtilityApplication',
    applicationSubCategory: toolSubcategory(route),
    operatingSystem: 'Any',
    browserRequirements:
      'Requires JavaScript. Audio tools require a microphone; compass and level require device sensors.',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
  };
}

function toolSubcategory(route: string): string {
  switch (route) {
    case '/guitar-tuner':
      return 'Music Tuner';
    case '/json-format':
    case '/json-to-yaml':
    case '/yaml-format':
    case '/regex':
    case '/string-escape':
      return 'Developer Tool';
    case '/time':
      return 'Reference';
    case '/jwt':
      return 'Security Tool';
    case '/compass':
      return 'Navigation';
    case '/ruler':
    case '/level':
      return 'Measurement';
    default:
      return 'Utility';
  }
}
